#149 side nav closing
Kanika637/amazon-clone pull request #150
Opened 2022-10-28 17:28 UTC by mecskyverse

# Description

Fixes:  #149 
Side bar Head is overlapping with sidebar body hence it is causing problem to close the Side Navbar. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.

---

## ATTACH SCREEN-SHOTS / DEPLOYMENT LINK:
Before
![image](https://user-images.githubusercontent.com/91150257/198697045-2bce515d-5180-45fe-978e-6943e761fb30.png)
After
![image](https://user-images.githubusercontent.com/91150257/198695595-0280465f-f325-4dd3-a25b-5f600029f267.png)

2022-10-28 17:33 UTC, mecskyverse commented
Hey! @Kanika637 can you review this one.

2022-10-29 04:45 UTC, Kanika637 requested changes

2022-10-29 04:45 UTC, Kanika637 commented on README.md
> +## Steps to making a pull request <a name = "raise_pr"></a>
```suggestion
## Steps for making a pull request <a name = "raise_pr"></a>
```

2022-10-29 04:45 UTC, Kanika637 commented on README.md
> +// #343 is the issu ticket number and make a request is the assigned issue name.
```suggestion
// "#343" is the issue ticket number and "make a request" is the assigned issue name.
```

2022-10-29 05:10 UTC, mecskyverse commented
It's my first time encountering a change request and I have added two commits as per your suggestion. Is it good to go or should I add something else?

2022-10-29 06:15 UTC, Kanika637 approved these changes
LGTM🚀

2022-10-29 06:15 UTC, Kanika637 commented
> It's my first time encountering a change request and I have added two commits as per your suggestion. Is it good to go or should I add something else?

Yes you did it right👍

2022-10-29 06:15 UTC, merged